### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by firestar115** [austinv11/Discord4J#174]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
After about 12 hours of running a bot using Discord4J the memory usage goes from about 8MB to 3GB.

### Steps to Reproduce
1. Create a bot that removes certain chat messages using Discord4J
2. Run it by double-clicking

...

**Expected behavior:** Not eating up half of my RAM.
**Actual behavior:** Eating up half of my RAM.

**Stacktrace (if applicable):** 

**Version affected:** 2.6.1

### Additional Information
Ubuntu 16.04
JDK 1.8.0_112

**Comment by theIglooo** [comment]
I don't think it's related to removing chat messages at all, it's probably one of the bugs in 2.6.1 that were fixed in the websocket-rewrite branch.

Highly recommended that you switch to that, it's the most stable branch at the moment and we're just working on fixing some other bugs before it's ready for release.
Version: `websocket-rewrite-SNAPSHOT`. Make sure you reimport whenever there's a new commit so you stay up-to-date with it.

**Comment by ArsenArsen** [comment]
I do not get this on WS-R, my bot runs on almost 600 servers with constant around 300-500MB RAM

**Comment by austinv11** [comment]
Closing this for now, if you can reproduce this on 2.7 please let us know.

**Comment by firestar115** [comment]
Ok
