### ISSUE TITLE
API Don't start

### ISSUE THREAD

**Issue by manercraft** [austinv11/Discord4J#188]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
The bot can't start, API generate error

### Steps to Reproduce
1. AyFilter.disc = AyFilter.getClient(true);

**Expected behavior:** No Error

**Actual behavior:** Got error

**Stacktrace (if applicable):** 
![totermw_2016-12-31_17-12-50](https://cloud.githubusercontent.com/assets/1338257/21578336/833a3dbc-cf7c-11e6-925e-90b492eff7d9.jpg)

**Version affected:** 2.7.0

**Comment by manercraft** [comment]
Same  issus on 2.6.1

**Comment by austinv11** [comment]
The issue occurs when a user with an invisible status is on a voice channel when the bot attempts to log in. I'm gonna have to look into fixing it somehow.

**Comment by GrandPanda** [comment]
Jake has said that this is a known issue that they will be fixing in the future. Members with voice states should be sent in guild_create. I'm reluctant to fix this for the time being because it would require fundamentally changing the way we construct guild objects only to change it back when Discord fixes it on their end.

**Comment by austinv11** [comment]
Fixed via 04ee66f
