### ISSUE TITLE
Role color

### ISSUE THREAD

**Issue by Jatboy** [austinv11/Discord4J#23]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [#java_discord4j channel on 
the Discord API Server](https://discord.gg/0SBTUU1wZTU7PCok)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
When setting a roles color it either does nothing at all or goes to the default color.

### Steps to Reproduce
1. Get a role and set its color.

**Expected behavior:**  The role color was supposed to be set to specified value.

**Actual behavior:**  Nothing or the color went to default.

**Stacktrace (if applicable):** 

**Version affected:** 2.4.4

**Comment by iabarca** [comment]
Can reproduce every time. The bug comes from Discord using only RGB to represent role color while java.awt.Color is providing an opacity value.

To remove the alpha part of the Color, Discord4J needs to use `color.getRGB() & 0x00ffffff` in the RoleEditRequest instead of ``color.getRGB()`` only.

https://github.com/austinv11/Discord4J/blob/master/src/main/java/sx/blah/discord/json/requests/RoleEditRequest.java#L34

**Comment by austinv11** [comment]
Thanks @iabarca for pointing this out 👍
