### ISSUE TITLE
Implement Message embed support

### ISSUE THREAD

**Issue by austinv11** [austinv11/Discord4J#95]
Currently embeds trigger a MessageUpdateEvent. There should be a separate event for this (maybe called `MessageEmbedEvent`?) which will contain the information regarding the embed for the message. Additionally, I should provide a POJO for embed objects

**Comment by robot-rover** [comment]
Austin I was doing some testing on this to see if I could try to implement this into D4J, but I couldn't get the MessageUpdateEvent to fire for embedding a youtube video by link or uploading a picture. Am I missing something or were you talking about a different type of embedding.

**Comment by robot-rover** [comment]
Ok so the MessageEmbedEvent is implemented and working, however, I have come across an interesting finding with the way discord handles embedding. If a link has been embedded in the past 7 or 6 messages (I'm not sure how many exactly) then Discord does not send a MESSAGE_UPDATE JSON to the client. It appears that recent embedded links are stored in some sort of cache, and if a link is in this cache, the embed information is sent with the inital message JSON instead of a MESSAGE_UPDATE JSON. I will work on having a message embed event fire even when the message has things embedded in it with the Inital MESSAGE_CREATE JSON.

**Comment by robot-rover** [comment]
Working on Implementing this fix: when D4J receives a MESSAGE_CREATE, if it contains embed information it automatically dispatches a MessageEmbedEvent.

**Comment by robot-rover** [comment]
Refer to Pull Request #96
